goose3/extractors/images.py

image url maybe not have scheme

check image scheme

---

CHANGELOG.md
goose3/__init__.py
goose3/configuration.py
goose3/crawler.py
goose3/network.py
goose3/utils/__init__.py

* Fix to initialize the `requests` connection once per Goose object
* Additional parameters to allow for proxies, authorization, and headers for the `requests` connection
* Update the `known_context_patterns` property handling to hopefully make it easier to add multiple new patterns

Fetcher update

---

.pylintrc
goose3/__init__.py
goose3/cleaners.py
goose3/extractors/authors.py
goose3/extractors/content.py
goose3/extractors/images.py
goose3/extractors/metas.py
goose3/extractors/publishdate.py
goose3/extractors/title.py
goose3/extractors/tweets.py
goose3/outputformatters.py
goose3/parsers.py
goose3/text.py
goose3/utils/encoding.py
goose3/utils/images.py

To leave the code in a slightly better way that I found it, I added a pylintrc file. Using pylint, I updated the code:
* Fix line continuations
* Class methods use cls instead of self
* Fixed using builtin names (all but one)
* Renamed some variables to be more informative
* Remove unused variables
More work should be done to keep it clean and maintainable long term, but this is a start
Also, fixed an error in passing fetcher around

basic pylint updates

---

goose3/configuration.py
tests/test_parsers.py

Add soup parser in AVAILABLE_PARSERS otherwise configuration example in README won't work.

add soup parser in AVAILABLE_PARSERS 

---

.pylintrc
CHANGELOG.md
goose3/__init__.py
goose3/cleaners.py
goose3/crawler.py
goose3/extractors/content.py
goose3/extractors/images.py
goose3/extractors/metas.py
goose3/extractors/tags.py
goose3/extractors/videos.py
goose3/image.py
goose3/utils/__init__.py
goose3/utils/encoding.py
goose3/utils/images.py
goose3/version.py
setup.py

* Continued to cleanup non-pythonic names and variables 
* have left function names alone
* Addressed some additional pylint suggestions for readability
* Removed a redefined builtin
* Update changelog

Additional Pylint cleanup

---

CHANGELOG.md
goose3/configuration.py
goose3/utils/images.py

* Catch additional PIL exceptions (really an OS error) #42 
* Correct the documentation

Catch additional PIL exceptions

---

CHANGELOG.md
goose3/article.py
goose3/crawler.py
goose3/extractors/metas.py
goose3/version.py
tests/data/metas/test_meta_encoding.html
tests/data/metas/test_meta_encoding.json
tests/test_metas.py

* Add some tests for the mismatch encoding
* Allow users to see the extracted encoding from the metadata

Version 3.1.3 version bump

---

goose3/article.py
goose3/crawler.py
goose3/extractors/images.py
goose3/extractors/publishdate.py
goose3/extractors/reportagenewsarticle.py
goose3/extractors/title.py
tests/data/images/test_reportagenewsarticle.html
tests/data/images/test_reportagenewsarticle.json
tests/data/opengraph/test_opengraph.json
tests/data/reportagenewsarticle/test_reportagenewsarticle.html
tests/data/reportagenewsarticle/test_reportagenewsarticle.json
tests/test_base.py
tests/test_images.py
tests/test_reportagenewsarticle.py

Support collecting article metadata from a valid ReportageNewsArticle
`application/ld+json` script.
Fixes: #62

Support schema.org's ReportageNewsArticle

---

goose3/crawler.py
goose3/extractors/opengraph.py
goose3/extractors/publishdate.py
tests/data/opengraph/test_opengraph_type.html
tests/data/opengraph/test_opengraph_type.json
tests/test_opengraph.py

- Parse out the opengraph type specific elements
- Populate the publish_date if the opengraph article::publish_date
exists in the opengraph dictionary
Fixes: #63

Parse additional opengraph type elements

---

goose3/configuration.py
goose3/extractors/publishdate.py
tests/data/publishdate/test_publish_date_parsely_page.html
tests/data/publishdate/test_publish_date_parsely_page.json
tests/data/publishdate/test_publish_date_tag.html
tests/data/publishdate/test_publish_date_tag.json
tests/test_publishdate.py

* Allow returning a tags content
* Allow parsing out subcontent out of a content tag with json
Fixes: #61

Improve publish date parsing

---

goose3/cleaners.py
goose3/configuration.py
goose3/crawler.py
goose3/extractors/content.py
goose3/extractors/images.py
goose3/extractors/title.py
goose3/network.py
goose3/utils/images.py

handle mismatch encode types

---

tests/data/opengraph/test_opengraph_type_none.html
tests/data/opengraph/test_opengraph_type_none.json
tests/test_opengraph.py

Should fail until #82 is merged.

Add test for Issue #81

---

goose3/crawler.py
goose3/extractors/images.py
goose3/extractors/schema.py
tests/data/images/test_reportagenewsarticle.json

See https://schema.org/NewsArticle and https://schema.org/Article

Add additional schema types for schema.org parser

---

goose3/configuration.py
goose3/extractors/authors.py
goose3/extractors/publishdate.py
tests/data/authors/test_author_config.html
tests/data/authors/test_author_config.json
tests/test_authors.py

* add one publish date tag
* fix extraction publish date
* extracting authors via KNOWN_AUTHOR_PATTERNS

publishdate extractor

---

goose3/extractors/content.py
tests/data/content/test_wiwo.html
tests/data/content/test_wiwo.json
tests/test_content.py

Update all parents (instead of only parent and parentparent) to not miss deeply nested content.

Update score of all parents

---

CHANGELOG.md
CONTRIBUTING.md
goose3/configuration.py
goose3/outputformatters.py
tests/test_base.py

Optional remove footnotes

---

CHANGELOG.md
goose3/extractors/title.py
goose3/version.py

resolves #123 
This is another attempt to fix 123 without changing current behavior, based on the test suite. 
@Pradhvan I tested against your test case also and it worked, can you see if this version solves 123 for you?

simple fix for title parsing

---

goose3/extractors/publishdate.py

Fix float offsets

---

.github/workflows/python-package.yml
goose3/crawler.py
requirements/python

fixes #106 
* Adds a new dependency: [langdetect](https://github.com/Mimino666/langdetect)

add basic lang detection

---

CHANGELOG.md
CONTRIBUTING.md
goose3/version.py

version bump v.3.1.11

---

.github/workflows/python-package.yml
goose3/__init__.py
goose3/configuration.py
goose3/crawler.py
goose3/extractors/publishdate.py
goose3/extractors/title.py
goose3/utils/__init__.py
setup.py

I've done a few to-do's spread here and there throughout the project. Biggest change - code wise - is refactoring the meta_lang and publish_date_to_utc logic to separate methods.

Basic logging, typing and deprecate python3.5 and 3.6

---

CHANGELOG.md
CONTRIBUTING.md
goose3/text.py

apply issue 139 fix

---

.pylintrc
goose3/__init__.py
goose3/article.py
goose3/cleaners.py
goose3/configuration.py
goose3/crawler.py
goose3/extractors/__init__.py
goose3/extractors/authors.py
goose3/extractors/content.py
goose3/extractors/images.py
goose3/extractors/links.py
goose3/extractors/metas.py
goose3/extractors/opengraph.py
goose3/extractors/publishdate.py
goose3/extractors/schema.py
goose3/extractors/tags.py
goose3/extractors/title.py
goose3/extractors/tweets.py
goose3/extractors/videos.py
goose3/image.py
goose3/network.py
goose3/outputformatters.py
goose3/parsers.py
goose3/text.py
goose3/utils/__init__.py
goose3/utils/encoding.py
goose3/utils/images.py
goose3/version.py
goose3/video.py

Utilizing the [pyupgrade](https://github.com/asottile/pyupgrade) tool to clean-up and modernize simple portions of the code-base. 
``` bash
pyupgrade --py36-plus goose3/*.py
```
The goal is once some items are cleaned up and standardized, hopefully it makes other improvements and enhancements possible.

Python 3.6-plus Standardization

---

.pylintrc
goose3/__init__.py
goose3/cleaners.py
goose3/configuration.py
goose3/crawler.py
goose3/extractors/authors.py
goose3/extractors/content.py
goose3/extractors/images.py
goose3/extractors/metas.py
goose3/extractors/opengraph.py
goose3/extractors/publishdate.py
goose3/extractors/title.py
goose3/extractors/videos.py
goose3/parsers.py
goose3/text.py
goose3/utils/__init__.py
goose3/utils/encoding.py
goose3/utils/images.py
pyproject.toml
tests/test_images.py

In an attempt to clean-up the library, I followed many of the [pylint](https://github.com/PyCQA/pylint) suggestions. This does not deal with all possible cleanups as some were suppressed. In the future, I would like to take on a few additional items:
* Access to protected members
* Remove camelCase function names to be more pythonic
* Perform [black](https://github.com/psf/black) formatting on the code base
* Flag/Tag unused functions for possible removal 
If these are done, I am hopeful that some of the longer standing issues could be easier to resolve. 
Some of these items could be added to Github Actions to become more automated to keep the library up to date. 
Thoughts?

python3 - pylint updates

---

goose3/extractors/title.py

See https://www.linkedin.com/pulse/you-getting-raise-year-cnbc/
This URL have this schema info:
```json
{
"@context": "http://schema.org",
"@type": "Article",
"headline": "Hello! And welcome to the CNBC Work It newsletter about all things work, from how to land the job to how to succeed in your career. This week’s topic is a pressing question: Are you getting a raise this year? If so, how much? With inflation soaring — egg prices have been so high, you might consider ",
"url": "https://www.linkedin.com/pulse/you-getting-raise-year-cnbc",
"publisher": null,
"name": "Are you getting a raise this year?",
"commentCount": 7,
"interactionStatistic": [
{
"interactionType": "http://schema.org/LikeAction",
"userInteractionCount": 245,
"@type": "InteractionCounter"
},
{
"interactionType": …
```

Title extraction: fix a bug when publisher=null lead to TypeError

---

goose3/network.py

ensure strict property is always used for 404

---

goose3/article.py
goose3/crawler.py

I think that this functionality can fix #112, adding top_node_raw we can have many good things -- example get all images inside article

#112 Add top node raw

---

.gitignore
goose3/extractors/schema.py

Pull request for the isse #167.

add @graph support for extracted linked data

---

goose3/extractors/schema.py

check for @type in linked_data

---

goose3/crawler.py
goose3/extractors/metas.py

resolves #181 
This ensures that it should only pull the first for the final_url parsing in metas.py

fix list of urls issue

---

CHANGELOG.md
goose3/__init__.py
goose3/cleaners.py
goose3/configuration.py

Remove `small` tokens 

---

goose3/extractors/authors.py

resolves https://github.com/goose3/goose3/issues/197

handle None author value

---

goose3/crawler.py

fix for multiple urls

---

goose3/extractors/schema.py

resolves https://github.com/goose3/goose3/issues/202

handle @graph as dict

---

goose3/extractors/title.py

resolves https://github.com/goose3/goose3/issues/206

handle article schema publisher value as a string #206

---

goose3/extractors/title.py

handle escape characters in article domain #209
